# a = float(input())
# b = float(input())
# MEDIA = (3.5*a + 7.5*b)/11
# print("MEDIA = %0.2f" %MEDIA)
a = int(input())
b = int(input())
c = int(input())
d = int(input())
DIFERENCA = a * b - c * d
print(f'DIFERENCA = {DIFERENCA}')