Algoritmo "exercicio51"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Algorítimo que escreve os números de 1 a 10 em ordem decrescente.
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 10 ate 1 passo -1 faca
escreva(contador)
fimpara

Fimalgoritmo