Algoritmo "exercico52"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Algorítimo que escreve os 10 primeiros números inteiros maiores que 100.
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 101 ate 110 faca
escreva(contador)
fimpara

Fimalgoritmo