Algoritmo "exercicio57"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Algorítimo que escreve os números de 1 a 10.
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
repita
contador <- contador + 1
escreva(contador)
ate contador = 10


Fimalgoritmo