Algoritmo "exercicio50"
// Disciplina   : [Lógica de Programação com javaScript]
// Professor   : Jailson
// Descrição   : Algorítmo que escreve os números de 1 a 10..
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contador de 1 ate 10 faca
escreva(contador)
FIMPARA



Fimalgoritmo