Algoritmo "exercicio55"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Programa que escreve a tabuada do 8 de 1 a 10.
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
numero : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero de 1 ate 10 faca
escreval("8 X" ,numero ," =" ,numero*8)
fimpara

Fimalgoritmo