Algoritmo "exercicio58"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Algorítimo que escreva os números de 1 a 10 em ordem decrescente.
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 10
enquanto contador >= 1 faca
escreva(contador)
contador <- contador - 1
fimenquanto

Fimalgoritmo