Algoritmo "ecercicio53"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Programa que escreve os números de 1 a n.
// Autor(a)    : Mailson
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
valorN : inteiro
n : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite N: ")
leia(n)
para valorN de 1 ate n faca
escreva(valorN)
fimpara

Fimalgoritmo